version: '3.3'
services:
  db:
    image: postgres:10.1
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3
    expose:
      - "6379"

  test:
    build: .
    volumes:
      - .:/swiftwind
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    links:
      - db
    command: ./manage.py test
    stdin_open: true
    tty: true
    networks:
      - default

  app:
    build: .
    volumes:
      - .:/swiftwind
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    links:
      - db
      - redis
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 example_project.wsgi
    volumes:
      - media:/swiftwind/.media

volumes:
  pgdata:
  media:
