apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "swiftwind.fullname" . }}-scheduler
  labels:
    app: {{ template "swiftwind.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "swiftwind.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['./manage.py', 'run_scheduler']
          env:
{{- if .Values.postgresql.enabled }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                # We shouldn't hard code 'postgresql' here, but the following:
                #    name: {{ template "postgresql.fullname" . }}
                # ...kept printing "bills-swiftwind" rather than "bills-postgresql"
                name: {{ printf "%s-postgresql" .Release.Name | trunc 63 | trimSuffix "-" }}
                key: postgres-password
          - name: POSTGRES_USER
            value: {{ default "postgres" .Values.postgresql.postgresUser | quote }}
          - name: POSTGRES_DB
            value: {{ default "" .Values.postgresql.postgresDatabase | quote }}
          - name: POSTGRES_HOST
            # See note above
            value: {{ printf "%s-postgresql" .Release.Name | trunc 63 | trimSuffix "-" }}
          - name: POSTGRES_PORT
            value: {{ .Values.postgresql.service.port | quote }}
{{- else }}
          - name: DATABASE_URL
            value: {{ .Values.database_url | quote }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
